// Local: src/shared/services/baserowClient.ts
export {};
// ESTE ARQUIVO PODE SER REMOVIDO OU ESVAZIADO
// TODAS AS OPERAÇÕES COM BASEROW DEVERIAM PASSAR PELO BACKEND POR SEGURANÇA.
// NENHUMA API KEY DEVE SER EXPOSTA NO FRONTEND.
